[graph]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[bans]
multiple-versions = "deny"
multiple-versions-include-dev = false
wildcards = "deny"
highlight = "all"

# Avoid noise from well-known build/test-only trees; our runtime guard handles prod paths.
skip-tree = [
	# docker/testcontainers path (dev-only)
	{ name = "bollard" },
	{ name = "testcontainers" },
]

skip = [
	{ name = "event-listener", reason = "sqlx uses v2.x while async-broadcast pulls v5.x via kube-runtime" },
	{ name = "linux-raw-sys", reason = "which uses rustix 0.38 -> linux-raw-sys 0.4, while tempfile pulls rustix 1.x -> linux-raw-sys 0.11" },
	{ name = "rustix", reason = "see linux-raw-sys explanation" },
	{ name = "nom", reason = "sqlformat depends on nom 7 while jsonschema depends on nom 8" },
]

[licenses]
confidence-threshold = 0.93
allow = [
	"MIT",
	"Apache-2.0",
	"BSD-3-Clause",
	"BSD-2-Clause",
	"ISC",
	"Unicode-DFS-2016",
	"Zlib",
]
exceptions = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
