###############################################
# cargo-deny configuration (baseline)
###############################################

[advisories]
# Ignore known issues for MVP - should be addressed in production
ignore = [
    "RUSTSEC-2025-0012", # backoff crate unmaintained - used by kube-runtime
    "RUSTSEC-2024-0388", # derivative crate unmaintained - used by kube-runtime  
    "RUSTSEC-2024-0384", # instant crate unmaintained - indirect dependency
    "RUSTSEC-2024-0436", # paste crate unmaintained - used by sqlx
    "RUSTSEC-2024-0363", # SQLx vulnerability - upgrade in production
]

[licenses]
# Updated configuration format for cargo-deny v0.13+
allow = [
    "MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", 
    "Unicode-3.0", "MPL-2.0", "Zlib"
]
exceptions = []
confidence-threshold = 0.8

[bans]
highlight = "all"
wildcards = "allow"
multiple-versions = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
