version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: aether-postgres
    environment:
      POSTGRES_USER: aether
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aether_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aether"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-00-00Z
    container_name: aether-minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: aether
      MINIO_ROOT_PASSWORD: aethersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
