apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aetherapps.aether.dev
spec:
  group: aether.dev
  scope: Namespaced
  names:
    plural: aetherapps
    singular: aetherapp
    kind: AetherApp
    shortNames:
      - aapp
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: AetherApp describes a deployable application managed by the Aether operator.
          properties:
            spec:
              type: object
              required: [image]
              properties:
                image:
                  type: string
                  description: Container image (including tag or digest) to deploy.
                replicas:
                  type: integer
                  format: int32
                  minimum: 0
                  description: Desired replica count (default 1 if omitted).
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                  format: int64
                lastReconcile:
                  type: string
                  description: RFC3339 timestamp of last successful reconcile.
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
