name: sidecar-image
on:
  push:
    branches:
      - feat/complete-aether-engine-mvp
    paths:
      - 'sidecar/**'
      - 'crates/json-extract/**'
      - 'crates/ed25519-verify/**'
      - '.github/workflows/sidecar-image.yml'
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/aether-dev-hot-sidecar:latest
          docker build -f sidecar/Dockerfile -t "$IMAGE" .
          docker push "$IMAGE"
      - name: Output image ref
        run: echo "published=$IMAGE" >> $GITHUB_OUTPUT