apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    app: {{ include "control-plane.name" . }}
data:
  {{- if .Values.config }}
{{ toYaml .Values.config | indent 2 }}
  {{- else }}
  {}
  {{- end }}
