apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "control-plane.fullname" . }}
  labels:
    app: {{ include "control-plane.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "control-plane.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "control-plane.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: control-plane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: RUST_LOG
              value: {{ .Values.env.RUST_LOG | quote }}
            - name: DATABASE_URL
{{- if .Values.env.DATABASE_URL }}
              value: {{ .Values.env.DATABASE_URL | quote }}
{{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.keys.url }}
{{- end }}
            - name: AETHER_API_TOKENS
              value: {{ .Values.env.TOKENS | quote }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
