{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
stringData:
  {{ .Values.secret.keys.url }}: {{ .Values.env.DATABASE_URL | default "" | quote }}
{{- end }}
