apiVersion: v1
kind: Service
metadata:
  name: {{ include "control-plane.fullname" . }}
spec:
  selector:
    app: {{ include "control-plane.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
